[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://smart-sales-system.onrender.com"